# Generated by Django 5.2 on 2025-12-13 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='cardano_record_hash',
            field=models.CharField(blank=True, help_text='Hash returned from Cardano when record is stored', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='cardano_tx_hash',
            field=models.CharField(blank=True, help_text='Transaction hash for CarePoints minting', max_length=128, null=True),
        ),
    ]
