# Generated by Django 5.2 on 2025-12-15 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_remove_appointment_updated_at_and_more'),
        ('patients', '0002_patientprofile_cardano_record_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='cardano_record_hash',
            field=models.CharField(blank=True, help_text='Hash of the medical record stored on Cardano', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='cardano_tx_hash',
            field=models.CharField(blank=True, help_text='Cardano transaction hash', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='created_by_doctor',
            field=models.ForeignKey(blank=True, help_text='Doctor who created this patient profile', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patients', to='doctors.doctorprofile'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='ipfs_hash',
            field=models.CharField(blank=True, help_text='IPFS hash of the medical record', max_length=128, null=True),
        ),
    ]
