# Generated by Django 5.2 on 2025-12-13 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_hospital', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('completed', 'Completed')], default='pending', max_length=32)),
                ('cardano_hash', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('packet_generated', models.BooleanField(default=False)),
                ('packet_file', models.FileField(blank=True, null=True, upload_to='referral_packets/')),
                ('notes', models.TextField(blank=True)),
                ('from_doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_referrals', to='doctors.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='patients.patientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicianThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referral', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thread', to='referrals.referral')),
            ],
        ),
        migrations.CreateModel(
            name='ThreadMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('text', 'Text'), ('voice', 'Voice'), ('image', 'Image')], default='text', max_length=16)),
                ('file', models.FileField(blank=True, null=True, upload_to='thread_files/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_thread_messages', to='doctors.doctorprofile')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='referrals.clinicianthread')),
            ],
        ),
    ]
