# Generated by Django 5.2 on 2025-12-13 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='cardano_address',
            field=models.CharField(blank=True, help_text='Cardano wallet address for receiving CarePoints', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='care_points_balance',
            field=models.IntegerField(default=0, help_text='Total CarePoints earned (synced from Cardano)'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='current_streak',
            field=models.IntegerField(default=0, help_text='Current consecutive days streak'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='last_record_date',
            field=models.DateField(blank=True, help_text='Last date a patient record was created (for streak tracking)', null=True),
        ),
    ]
