# Generated by Django 5.2 on 2025-12-15 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_appointment_carepointstransaction'),
        ('patients', '0002_patientprofile_cardano_record_hash_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='patients.patientprofile'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_name',
            field=models.CharField(blank=True, help_text='For cases where patient profile might not exist yet', max_length=255),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='carepointstransaction',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='carepointstransaction',
            name='transaction_type',
            field=models.CharField(choices=[('patient_record', 'Patient Record Creation'), ('referral_sent', 'Referral Sent'), ('referral_accepted', 'Referral Accepted'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
